# Generated by Django 5.2.4 on 2025-08-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_joinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='request_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('request', 'Request')], default='request', max_length=10),
        ),
    ]
