# Generated by Django 5.2.4 on 2025-08-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.CharField(choices=[('0', 'dislike'), ('1', 'like'), ('2', 'love')], max_length=10),
        ),
    ]
