# Generated by Django 5.2.4 on 2025-08-05 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_average_rating_movie_total_ratings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.CharField(choices=[('0', 'dislike'), ('1', 'like'), ('2', 'love'), ('3', 'watched')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='room',
        ),
    ]
