# Generated by Django 5.2.4 on 2025-08-06 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movierating_unique_together_and_more'),
        ('rooms', '0004_joinrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movierating',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user', 'movie', 'room')},
        ),
    ]
