# Generated by Django 5.2.4 on 2025-08-07 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movierating_unique_together_movierating_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user', 'movie')},
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='room',
        ),
    ]
