# Generated by Django 5.2.4 on 2025-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movierating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
