# Generated by Django 5.2.4 on 2025-08-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_background_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='background_url',
        ),
    ]
