# Generated by Django 5.2.4 on 2025-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_background_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.CharField(choices=[('0', 'dislike'), ('0', 'watched'), ('1', 'like'), ('2', 'love')], max_length=10),
        ),
    ]
