# Generated by Django 5.2.4 on 2025-08-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movierating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.CharField(choices=[('0', 'dislike'), ('1', 'like'), ('2', 'love'), ('3', 'watched')], max_length=10),
        ),
    ]
