# Generated by Django 5.2.4 on 2025-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movierating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.CharField(choices=[('0', 'dislike'), ('1', 'like'), ('2', 'love')], max_length=10),
        ),
    ]
