# Generated by Django 5.2.4 on 2025-08-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movierating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'dislike'), (1, 'like'), (2, 'love')], null=True),
        ),
    ]
